### ISSUE TITLE
As a user, I want to make a post to my timeline

### ISSUE THREAD

**Issue by liubryann** [liubryann/timeline#4]
-  [ ] https://github.com/liubryann/timeline/issues/5
- [ ] https://github.com/liubryann/timeline/issues/6
- [ ] https://github.com/liubryann/timeline/issues/7
- [ ] https://github.com/liubryann/timeline/issues/9
- [ ] https://github.com/liubryann/timeline/issues/8
